








<table>


 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid','informant','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('genre','situasjon', 'hidden')</script></td>
 </tr>
</table>
<hr>
<table width="100%">
 <tr>
  <td valign="top" width="33%"><script language="javascript">writeWidgetDoubleTable('bred','oppvokst','hidden')</script> </td>
  <td valign="top" width="33%"><script language="javascript">writeWidgetDoubleTable('abode','bosted','hidden')</script> </td>
  <td valign="top" width="33%"><script language="javascript">writeWidgetDoubleTable('longest','bodd lengst', 'hidden')</script></td>
 </tr>
</table>
<table>
<hr>
 <tr>
<!--   <td valign="top"><script language="javascript">writeWidgetFromTo('age','alder', 'hidden')</script>    </td>-->
  <td valign="top"><script language="javascript">writeWidgetCheck('agegroup','aldersgruppe', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetCheck('sex','kjønn', 'hidden')</script> </td>
 </tr>
</table>
<table>
<hr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetCheck('edu','utdannelse', 'hidden')</script>    </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('pro','yrke', 'hidden')</script></td>
</tr>
</table>
<table>


 <tr>



 </tr>

 <tr>

 </tr>
</table>
